name : cramped_room
lr: 1e-3
lr_disc: 1e-4
init_lambda: 1
min_lambda: 0.05
anneal_lr_fraction: 3.0
z_dim: 6
observation_shape: [26, 5, 4]

rshaped_horizon: 2.5e6
soup_reward: True
soup_reward_decay: False
ingred_reward: True
ingred_reward_decay: False

sp_timesteps: 6e6