name : riayn
trainer : 
  _target_ : trainers.riayn_trainer.RIAYNTrainer
runner : 
  _target_ : runners.riayn_runner.RIAYNRunner
hi_agent:
  _target_: modules.agents.HiAgent
lo_agent:
  _target_: modules.agents.LoAgent
discriminator:
  _target_: modules.agents.Discriminator
partner :
  _target_: modules.agents.CNNAgent

total_timesteps: 1e7